config/routes.rb
Rails.application.routes.draw do
  get 'search' => 'search#index', as: 'search'

  #get 'search/index'=> 'items#search', as: 'search/index'

  resources :item_inventories
  resources :items
  resources :fabrics
  resources :products

  get 'search/new'
  #get 'search/Item.search(search)'

  #items.search
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/fabric.rb
class Fabric < ApplicationRecord
  has_many :items
  has_many :item_inventories, through: :items

  def to_s
    self.name
  end

  def self.search(search)
    where("name LIKE ? OR sku LIKE ?", "%#{search}%", "%#{search}%")
  end
end

app/controllers/fabrics_controller.rb
class FabricsController < ApplicationController
  before_action :set_fabric, only: [:show, :edit, :update, :destroy]

  # GET /fabrics
  # GET /fabrics.json
  def index
    @fabrics = Fabric.all
  end

  # GET /fabrics/1
  # GET /fabrics/1.json
  def show
  end

  # GET /fabrics/new
  def new
    @fabric = Fabric.new
  end

  # GET /fabrics/1/edit
  def edit
  end

  # POST /fabrics
  # POST /fabrics.json
  def create
    @fabric = Fabric.new(fabric_params)

    respond_to do |format|
      if @fabric.save
        format.html { redirect_to @fabric, notice: 'Fabric was successfully created.' }
        format.json { render :show, status: :created, location: @fabric }
      else
        format.html { render :new }
        format.json { render json: @fabric.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fabrics/1
  # PATCH/PUT /fabrics/1.json
  def update
    respond_to do |format|
      if @fabric.update(fabric_params)
        format.html { redirect_to @fabric, notice: 'Fabric was successfully updated.' }
        format.json { render :show, status: :ok, location: @fabric }
      else
        format.html { render :edit }
        format.json { render json: @fabric.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fabrics/1
  # DELETE /fabrics/1.json
  def destroy
    @fabric.destroy
    respond_to do |format|
      format.html { redirect_to fabrics_url, notice: 'Fabric was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fabric
      @fabric = Fabric.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fabric_params
      params.require(:fabric).permit(:name, :sku)
    end
end

app/helpers/fabrics_helper.rb
module FabricsHelper
end

app/views/fabrics/_form.html.erb
<%= form_for(fabric) do |f| %>
  <% if fabric.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fabric.errors.count, "error") %> prohibited this fabric from being saved:</h2>

      <ul>
      <% fabric.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :sku %>
    <%= f.text_field :sku %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fabrics/edit.html.erb
<h2>Editing Fabric</h2>

<%= render 'form', fabric: @fabric %>

<%= link_to 'Show', @fabric %> |
<%= link_to 'Back', fabrics_path %>

app/views/fabrics/index.html.erb
<p id="notice"><%= notice %></p>

<header>Fabrics</header>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Sku</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fabrics.each do |fabric| %>
      <tr>
        <td><%= fabric.name %></td>
        <td><%= fabric.sku %></td>
        <td><%= link_to 'Show', fabric %></td>
        <td><%= link_to 'Edit', edit_fabric_path(fabric) %></td>
        <td><%= link_to 'Destroy', fabric, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fabric', new_fabric_path %>

app/views/fabrics/new.html.erb
<%= content_for :h2, 'New Fabric' %>

<%= render 'form', fabric: @fabric %>

<%= link_to 'Back', fabrics_path %>

app/views/fabrics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @fabric.name %>
</p>

<p>
  <strong>Sku:</strong>
  <%= @fabric.sku %>
</p>

<%= link_to 'Edit', edit_fabric_path(@fabric) %> |
<%= link_to 'Back', fabrics_path %>