config/routes.rb
Rails.application.routes.draw do
  get 'search' => 'search#index', as: 'search'

  #get 'search/index'=> 'items#search', as: 'search/index'

  resources :item_inventories
  resources :items
  resources :fabrics
  resources :products

  get 'search/new'
  #get 'search/Item.search(search)'

  #items.search
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :product
  belongs_to :fabric
  has_many :item_inventories, dependent: :destroy

  accepts_nested_attributes_for :product, reject_if: lambda {|attributes| attributes['name'].blank? || attributes['sku'].blank?}
  accepts_nested_attributes_for :fabric, reject_if: lambda {|attributes| attributes['name'].blank? || attributes['sku'].blank?}

  def to_s
    return "#{self.product} - #{self.fabric}"
  end

  def name
    self.to_s
  end

  def self.search(search)
    results=Fabric.search(search)
    results+=Product.search(search)
    results.map(&:items).flatten
  end

  # def product_attributes=(attributes)
  #   self.build_product(attributes)
  # end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
    @item.build_product
    # @item = []
    # 5.times do
    # @item << Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.find_or_initialize_by(item_params)

    respond_to do |format|
      if @item.save
        #params.each do|product_id:, fabric_id:|
        #  quantity.times do

        quantity = params[:quantity].to_i
        quantity.times do
          @item.item_inventories.create(notes: params[:notes])
        end

        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:product_id, :fabric_id, product_attributes: [:name, :sku], fabric_attributes: [:name, :sku])
    end
  end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for(item) do |f| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %>
    <%= f.select(:product_id, Product.all.collect {|p| [ p.name, p.id ] }, { include_blank: true }) %>
    <%#= f.fields_for :product do |product_form| %>
      <%#= product_form.text_field :name %>
      <%#= product_form.text_field :sku %>
    <%# end %>
  </div>

  <div class="field">
    <%= f.label :fabric_id %>
    <%= f.select(:fabric_id, Fabric.all.collect {|p| [ p.name, p.id ] }, { include_blank: true }) %>
  </div>

  <div class="field">
    <%= label_tag "How Many?" %>
    <%= number_field_tag :quantity, min: 0 %>
    <%#=  number_field_tag "#{thing}", :quantity, min: 0, placeholder: 0 %>
  </div>

  <div class="field">
    <%= label_tag 'Notes' %><br>
    <%= text_area_tag :notes %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<%= content_for :h2, 'Editing Item' %>


<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<%= content_for :h2, 'Items' %>


<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Fabric</th>
      <th>Number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.product.name %></td>
        <td><%= item.fabric.name %></td>
        <td><%= item.item_inventories.count %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<%= content_for :h2, 'New Item' %>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @item.product %>
</p>

<p>
  <strong>Fabric:</strong>
  <%= @item.fabric %>
</p>

<p>
  <strong>Number:</strong>
  <%= @item.item_inventories.count %>
</p>

<table>
  <thead>
    <tr>
      <th>Item</th>
      <th>Purchased at</th>
      <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @item.item_inventories.each do |item_inventory| %>
      <tr>
        <td><%= item_inventory.item.name %></td>
        <td><%= item_inventory.purchased_at %></td>
        <td><%= item_inventory.notes %></td>
        <td><%= link_to 'Show', item_inventory %></td>
        <td><%= link_to 'Edit', edit_item_inventory_path(item_inventory) %></td>
        <td><%= link_to 'Destroy', item_inventory, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%# Create table/list of all inventory items (@item.item_inventories) %>



<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>